name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:
    inputs:
      repository_url:
        description: 'GitHub Repository URL'
        required: true
      cloudflare_api_token:
        description: 'Cloudflare API Token'
        required: true
      cloudflare_account_id:
        description: 'Cloudflare Account ID'
        required: true
      cloudflare_project_name:
        description: 'Cloudflare Pages Project Name'
        required: true
      github_token:
        description: 'GitHub Token'
        required: true
      app_id:
        description: 'App ID'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.inputs.repository_url }}
          token: ${{ github.event.inputs.github_token }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: |
          if ! pnpm run build; then
            echo "Build failed"
            exit 1
          fi
          if [ ! -d "dist" ]; then
            echo "Error: dist directory not found"
            exit 1
          fi

      - name: Check if Cloudflare Pages project exists
        id: check_project
        run: |
          response=$(curl -s -X GET \
            "https://api.cloudflare.com/client/v4/accounts/${{ github.event.inputs.cloudflare_account_id }}/pages/projects/${{ github.event.inputs.cloudflare_project_name }}" \
            -H "Authorization: Bearer ${{ github.event.inputs.cloudflare_api_token }}" \
            -H "Content-Type: application/json")
          
          echo "Response: $response"
          
          # Check if project exists
          if echo "$response" | grep -q '"success":true'; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Project exists"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Project does not exist"
          fi

      - name: Create Cloudflare Pages project
        if: steps.check_project.outputs.exists == 'false'
        run: |
          echo "Creating Cloudflare Pages project: ${{ github.event.inputs.cloudflare_project_name }}"
          response=$(curl -s -X POST \
            "https://api.cloudflare.com/client/v4/accounts/${{ github.event.inputs.cloudflare_account_id }}/pages/projects" \
            -H "Authorization: Bearer ${{ github.event.inputs.cloudflare_api_token }}" \
            -H "Content-Type: application/json" \
            -d "{\"name\":\"${{ github.event.inputs.cloudflare_project_name }}\"}")
          
          echo "Create response: $response"
          
          if echo "$response" | grep -q '"success":true'; then
            echo "Project created successfully"
          else
            echo "Failed to create project"
            echo "$response"
            exit 1
          fi

      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ github.event.inputs.cloudflare_api_token }}
          accountId: ${{ github.event.inputs.cloudflare_account_id }}
          projectName: ${{ github.event.inputs.cloudflare_project_name }}
          directory: dist
          gitHubToken: ${{ github.event.inputs.github_token }}

      - name: Send notification to Genfly
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ] && [ "${{ steps.deploy.outcome }}" == "success" ]; then
            STATUS="completed"
          else
            STATUS="failed"
          fi
          curl -X POST https://www.genfly.dev/api/send \
            -H "Content-Type: application/json" \
            -d "{\"clientId\": \"${{ github.event.inputs.app_id }}\", \"status\": \"$STATUS\"}"