name: Restart and Deploy to Fly.io

on:
  workflow_dispatch:
    inputs:
      source_repo_url:
        description: "URL of the GitHub repository to deploy"
        required: true
        default: "https://github.com/fly-apps/hello-fly.git"
      github_token:
        description: "GitHub Personal Access Token with repo permissions"
        required: true
      fly_api_token:
        description: "Fly.io API Token for deployment"
        required: true
      fly_app_name:
        description: "Name of the Fly.io app to deploy to"
        required: true
        default: "my-fly-app"
      docker_image:
        description: "Docker image to deploy (e.g., registry.fly.io/my-app:latest)"
        required: true
        default: "registry.fly.io/ancodeai-app:latest"
      client_id:
        description: "Client ID for state tracking"
        required: true
        default: "workflow-client"

jobs:
  restart-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send start deployment state callback
        run: |
          RESPONSE=$(curl -X POST \
            -H "Content-Type: application/json" \
            "https://www.needware.dev/api/startup-callback" \
            -d '{
              "event": "start_deployment",
              "status": "started",
              "clientId": "${{ github.event.inputs.client_id }}",
              "source_repo": "${{ github.event.inputs.source_repo_url }}",
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }' \
            -w "%{http_code}" -s -o response.json)
          echo "Callback HTTP Status: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ] && [ "$RESPONSE" -ne 201 ]; then
            echo "Failed to send start deployment callback. Response:"
            cat response.json
            echo "Continuing workflow..."
          fi

      - name: Checkout workflow repository
        uses: actions/checkout@v4

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: "0.3.94"

      - name: Create fly.toml for deployment
        run: |
          cat << 'EOF' > fly.toml
          app = '${{ github.event.inputs.fly_app_name }}'
          primary_region = 'sin'
          [build]
            image = '${{ github.event.inputs.docker_image }}'
          [http_service]
            internal_port = 8080
            force_https = true
            auto_stop_machines = 'suspend'
            auto_start_machines = true
            min_machines_running = 0
            max_machines_running = 1
            processes = ['app']
          [[vm]]
            memory = '2gb'
            cpu_kind = 'shared'
            cpus = 1
            memory_mb = 2048
          EOF
          echo "Created fly.toml with image ${{ github.event.inputs.docker_image }}:"
          cat fly.toml

      - name: Check if Fly.io app exists
        env:
          FLY_API_TOKEN: ${{ github.event.inputs.fly_api_token }}
        run: |
          echo "Checking if Fly.io app exists: ${{ github.event.inputs.fly_app_name }}"
          flyctl apps list | grep "${{ github.event.inputs.fly_app_name }}" || {
            echo "App does not exist, creating it..."
            flyctl apps create ${{ github.event.inputs.fly_app_name }} --org needware || {
              echo "Failed to create app. Sending failure callback..."
              curl -X POST \
                -H "Content-Type: application/json" \
                "https://www.needware.dev/api/startup-callback" \
                -d '{
                  "event": "create_fly_app",
                  "status": "failed_to_create",
                  "clientId": "${{ github.event.inputs.client_id }}",
                  "app_name": "${{ github.event.inputs.fly_app_name }}",
                  "error": "Failed to create Fly.io app",
                  "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
                }' \
                -w "%{http_code}" -s
              exit 1
            }
            echo "App created successfully"
          }

      - name: Deploy initial Docker image to Fly.io
        env:
          FLY_API_TOKEN: ${{ github.event.inputs.fly_api_token }}
        run: |
          echo "Deploying initial Docker image to Fly.io app: ${{ github.event.inputs.fly_app_name }}"
          flyctl deploy --app ${{ github.event.inputs.fly_app_name }} --remote-only || {
            echo "Initial deployment failed. Sending failure callback..."
            curl -X POST \
              -H "Content-Type: application/json" \
              "https://www.needware.dev/api/startup-callback" \
              -d '{
                "event": "deploy_fly_app",
                "status": "failed_to_deploy",
                "clientId": "${{ github.event.inputs.client_id }}",
                "app_name": "${{ github.event.inputs.fly_app_name }}",
                "error": "Failed to deploy initial Docker image to Fly.io",
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
              }' \
              -w "%{http_code}" -s
            echo "Initial deployment failed. Fly.io status:"
            flyctl status --app ${{ github.event.inputs.fly_app_name }}
            exit 1
          }
          echo "Initial deployment successful"
      - name: Send initial deploy state callback
        run: |
          RESPONSE=$(curl -X POST \
            -H "Content-Type: application/json" \
            "https://www.needware.dev/api/startup-callback" \
            -d '{
              "event": "deploy_fly_app",
              "status": "deployed",
              "clientId": "${{ github.event.inputs.client_id }}",
              "app_name": "${{ github.event.inputs.fly_app_name }}",
              "app_url": "https://${{ github.event.inputs.fly_app_name }}.fly.dev",
              "docker_image": "${{ github.event.inputs.docker_image }}",
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }' \
            -w "%{http_code}" -s -o response.json)
          echo "Callback HTTP Status: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ] && [ "$RESPONSE" -ne 201 ]; then
            echo "Failed to send initial deploy callback. Response:"
            cat response.json
            echo "Continuing workflow..."
          fi

      - name: Scale Fly.io app to 1 machine
        env:
          FLY_API_TOKEN: ${{ github.event.inputs.fly_api_token }}
        run: |
          echo "Scaling Fly.io app ${{ github.event.inputs.fly_app_name }} to 1 machine"
          flyctl scale count 1 --app ${{ github.event.inputs.fly_app_name }} --yes || {
            echo "Failed to scale app. Sending failure callback..."
            curl -X POST \
              -H "Content-Type: application/json" \
              "https://www.needware.dev/api/startup-callback" \
              -d '{
                "event": "scale_fly_app",
                "status": "failed_to_scale",
                "clientId": "${{ github.event.inputs.client_id }}",
                "app_name": "${{ github.event.inputs.fly_app_name }}",
                "error": "Failed to scale to 1 machine",
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
              }' \
              -w "%{http_code}" -s
            echo "Failed to scale app. Current status:"
            flyctl status --app ${{ github.event.inputs.fly_app_name }}
            exit 1
          }
          echo "Successfully scaled to 1 machine"
      - name: Send scale state callback
        run: |
          RESPONSE=$(curl -X POST \
            -H "Content-Type: application/json" \
            "https://www.needware.dev/api/startup-callback" \
            -d '{
              "event": "scale_fly_app",
              "status": "scaled",
              "clientId": "${{ github.event.inputs.client_id }}",
              "app_name": "${{ github.event.inputs.fly_app_name }}",
              "machine_count": 1,
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }' \
            -w "%{http_code}" -s -o response.json)
          echo "Callback HTTP Status: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ] && [ "$RESPONSE" -ne 201 ]; then
            echo "Failed to send scale callback. Response:"
            cat response.json
            echo "Continuing workflow..."
          fi

      - name: Reset Fly.io Wireguard
        env:
          FLY_API_TOKEN: ${{ github.event.inputs.fly_api_token }}
        run: |
          echo "Resetting Fly.io Wireguard connection"
          flyctl wireguard reset || {
            echo "Failed to reset wireguard. Sending failure callback..."
            curl -X POST \
              -H "Content-Type: application/json" \
              "https://www.needware.dev/api/startup-callback" \
              -d '{
                "event": "reset_wireguard",
                "status": "failed_to_reset",
                "clientId": "${{ github.event.inputs.client_id }}",
                "app_name": "${{ github.event.inputs.fly_app_name }}",
                "error": "Failed to reset Wireguard",
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
              }' \
              -w "%{http_code}" -s
            echo "Continuing anyway..."
          }
          flyctl wireguard websockets enable || {
            echo "Failed to enable wireguard websockets. Sending failure callback..."
            curl -X POST \
              -H "Content-Type: application/json" \
              "https://www.needware.dev/api/startup-callback" \
              -d '{
                "event": "enable_wireguard_websockets",
                "status": "failed_to_enable",
                "clientId": "${{ github.event.inputs.client_id }}",
                "app_name": "${{ github.event.inputs.fly_app_name }}",
                "error": "Failed to enable Wireguard websockets",
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
              }' \
              -w "%{http_code}" -s
            echo "Continuing anyway..."
          }
          echo "Wireguard reset completed"
      - name: Send Wireguard state callback
        run: |
          RESPONSE=$(curl -X POST \
            -H "Content-Type: application/json" \
            "https://www.needware.dev/api/startup-callback" \
            -d '{
              "event": "reset_wireguard",
              "status": "reset",
              "clientId": "${{ github.event.inputs.client_id }}",
              "app_name": "${{ github.event.inputs.fly_app_name }}",
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }' \
            -w "%{http_code}" -s -o response.json)
          echo "Callback HTTP Status: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ] && [ "$RESPONSE" -ne 201 ]; then
            echo "Failed to send Wireguard callback. Response:"
            cat response.json
            echo "Continuing workflow..."
          fi

      - name: Login to Fly.io machine and setup GitHub repository
        env:
          FLY_API_TOKEN: ${{ github.event.inputs.fly_api_token }}
        run: |
          echo "Logging into Fly.io machine for app: ${{ github.event.inputs.fly_app_name }}"
          GITHUB_REMOTE_URL="https://${{ github.event.inputs.github_token }}@github.com/$(echo '${{ github.event.inputs.source_repo_url }}' | sed 's|https://github.com/||' | sed 's|\.git$||')"
          echo "GitHub repository URL: $GITHUB_REMOTE_URL"
          
          flyctl ssh console --app ${{ github.event.inputs.fly_app_name }} -C "sh -c '\
            echo \"Setting up Git configuration...\"; \
            git config --global init.defaultBranch main; \
            git config --global user.email \"github-actions[bot]@users.noreply.github.com\"; \
            git config --global user.name \"GitHub Actions Bot\"; \
            echo \"Current directory contents:\"; \
            ls -la; \
            echo \"Cloning GitHub repository: $GITHUB_REMOTE_URL\"; \
            if [ -d .git ]; then \
              echo \"Git repository already exists, updating...\"; \
              git remote set-url origin $GITHUB_REMOTE_URL; \
              git remote -v; \
              git fetch origin; \
              git reset --hard origin/main; \
            else \
              echo \"Initializing new git repository...\"; \
              git init; \
              git remote add origin $GITHUB_REMOTE_URL; \
              git remote -v; \
              git fetch origin; \
              git reset --hard origin/main; \
            fi; \
            echo \"Repository setup complete. Current directory contents:\"; \
            ls -la; \
            echo \"Checking for package.json...\"; \
            if [ -f package.json ]; then \
              echo \"Found package.json, installing dependencies with pnpm...\"; \
              npm install -g pnpm; \
              pnpm install; \
              echo \"Dependencies installed successfully\"; \
            else \
              echo \"No package.json found, skipping pnpm install\"; \
            fi; \
            echo \"Final directory contents:\"; \
            ls -la'" || {
            echo "Failed to login or setup GitHub repository. Sending failure callback..."
            curl -X POST \
              -H "Content-Type: application/json" \
              "https://www.needware.dev/api/startup-callback" \
              -d '{
                "event": "setup_fly_machine",
                "status": "failed_to_setup",
                "clientId": "${{ github.event.inputs.client_id }}",
                "app_name": "${{ github.event.inputs.fly_app_name }}",
                "error": "Failed to login or setup GitHub repository",
                "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
              }' \
              -w "%{http_code}" -s
            echo "Fly.io status:"
            flyctl status --app ${{ github.event.inputs.fly_app_name }}
            exit 1
          }
          echo "Successfully setup GitHub repository and installed dependencies"
      - name: Send setup Fly.io machine state callback
        run: |
          RESPONSE=$(curl -X POST \
            -H "Content-Type: application/json" \
            "https://www.needware.dev/api/startup-callback" \
            -d '{
              "event": "setup_fly_machine",
              "status": "setup_complete",
              "clientId": "${{ github.event.inputs.client_id }}",
              "app_name": "${{ github.event.inputs.fly_app_name }}",
              "repo_url": "${{ github.event.inputs.source_repo_url }}",
              "timestamp": "'$(date -u +"%Y-%m-%dT%H:%M:%SZ")'"
            }' \
            -w "%{http_code}" -s -o response.json)
          echo "Callback HTTP Status: $RESPONSE"
          if [ "$RESPONSE" -ne 200 ] && [ "$RESPONSE" -ne 201 ]; then
            echo "Failed to send setup Fly.io machine callback. Response:"
            cat response.json
            echo "Continuing workflow..."
          fi

      - name: Verify deployment
        run: |
          echo "Successfully created Fly.io machine and deployed from: ${{ github.event.inputs.source_repo_url }}"
          echo "Deployed to: https://${{ github.event.inputs.fly_app_name }}.fly.dev"
          echo "Machine is now bound to GitHub repository and dependencies are installed"