name: Revert Commit in Remote Repo

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'The commit SHA to revert'
        required: true
      branch:
        description: 'The branch to operate on'
        required: true
      repo_name:
        description: 'The repository name (e.g., genfly-${appName})'
        required: true
      github_token:
        description: 'The GitHub token for authentication'
        required: true

jobs:
  revert-remote:
    runs-on: ubuntu-latest
    steps:
      - name: Clone source repository
        run: |
          git clone https://x-access-token:${{ github.event.inputs.github_token }}@github.com/${{ github.repository_owner }}/${{ github.event.inputs.repo_name }} /tmp/source-repo
          cd /tmp/source-repo
          git checkout ${{ github.event.inputs.branch }}

      - name: Setup Git config
        run: |
          cd /tmp/source-repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Revert specified commit
        run: |
          cd /tmp/source-repo
          git fetch --all
          git revert ${{ github.event.inputs.commit_sha }} --no-edit

      - name: Push changes
        run: |
          cd /tmp/source-repo
          git push origin ${{ github.event.inputs.branch }}